---
# --------------------( LICENSE                           )--------------------
# Copyright (c) 2014-2020 Cecil Curry.
# See "LICENSE" for further details.
#
# --------------------( SYNOPSIS                          )--------------------
# GitHub-specific continuous integration (CI) configuration, enabling the usual
# GitHub Actions workflow for pure-Python packages exercised by "tox".
#
# --------------------( SEE ALSO                          )--------------------
# * https://hynek.me/articles/python-github-actions
#   Well-authored blog post strongly inspiring this configuration.

# ....................{ METADATA                          }....................
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# WARNING: Changes to this name *MUST* be manually synchronized with:
# * The "|GitHub Actions badge|" image URL in the top-level "README.rst".
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# Non-human-readable (i.e., machine-readable) label associated with this
# GitHub Actions workflow.
name: tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# ....................{ MAIN                              }....................
jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"

    #FIXME: As required, generalize to macOS and Windows by:
    #* Uncommenting the following line here:
    #runs-on: ${{ matrix.platform }}
    #* Uncommenting the "strategy/matrix/platform" line below.
    #* Replacing the "envlist" setting in "tox.ini" with something resembling:
    #    envlist = py3{5,6,7,8}-{linux,macos,windows},pypy3-{linux,macos,windows}
    runs-on: ubuntu-latest

    # ..................{ VARIABLES                         }..................
    #FIXME: Uncomment after properly researching code coverage integration.
    #On doing so, add "coverage[toml]" to the set of Python packages
    #installed with "pip" below.
    #env:
    #  USING_COVERAGE: '3.6,3.8'

    # ..................{ MATRIX                            }..................
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    # WARNING: Changes to this section *MUST* be manually synchronized with:
    # * The "[tox]" and "[gh-actions]" subsections of "tox.ini".
    #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    strategy:
      matrix:
        # platform: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.5, 3.6, 3.7, 3.8, pypy3]

    # ..................{ PROCESS                           }..................
    steps:
    - name: "Checking out repository..."
      uses: 'actions/checkout@v2'
    - name: "Installing Python ${{ matrix.python-version }}..."
      uses: 'actions/setup-python@v1'
      with:
        python-version: '${{ matrix.python-version }}'

    # Note that:
    #
    # * "set -xe" enables Bash:
    #   * Reporting (i.e., "-x"), which implicitly prints each command to
    #     stdout *BEFORE* running that command.
    #   * Strictness (i.e., "-e").
    # * Packaging dependencies (e.g., "pip") are installed *BEFORE* all
    #   remaining dependencies (e.g., "tox"), which include:
    #   * "numpy", enabling conditional unit tests requiring NumPy.
    #   * "tox-gh-actions", automating integration of GitHub Actions and "tox".
    - name: 'Installing package dependencies...'
      run: |
        set -xe
        python -VV
        python -m site
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade numpy virtualenv tox tox-gh-actions
    - name: 'Testing package with "tox"...'
      run: |
        python -m tox
